# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='classics_course',
            field=models.CharField(default='', max_length=50, verbose_name='\u7ecf\u5178\u8bfe\u7a0b'),
        ),
    ]
