# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170417_1631'),
        ('courses', '0002_auto_20170415_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseOrg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
