# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courseorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/courses/%y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
